### ISSUE TITLE
Feature: Celsius Toggle Option

### ISSUE THREAD

**Issue by nkrasn** [digitalcircuits/Open-Weather-Panel#5]
Some people prefer Celsius, especially in other countries. It would be nice if there was an option to toggle between Fahrenheit and Celsius.

**Comment by digitalcircuits** [comment]
At the time, it was a small project for myself but since you brought it up, it would be nice to have a toggle option between Fahrenheit and Celsius. I do not have time to add the option now but, if you have some time, I would be more than happy to approve this feature if you submit a PR.
